### PR TITLE
Adding some test files that can demo all existing features.

### PR DESCRIPTION
**Pull request by heejaechang**
these are some basic one to discuss and set pattern.

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]
Looks great to me :)

**Comment by StellaHuang95** [comment]
So what are the things that can't be caught by putting those tests in our fourslash/jest test suites?

**Comment by heejaechang** [comment]
alright, then I will keep adding stuff to the test projects.

**Review by StellaHuang95 — APPROVED** [review]

**Comment by heejaechang** [comment]
> So what are the things that can't be caught by putting those tests in our fourslash/jest test suites?

you can get all these things tested on our unit test and unit test should cover things in more detail. this is more sanity test (make sure things work in real vscode not just in unit test hardness) and these thing can also be automated using UI integration test (a test that uses vscode itself to test)

**Pull request merged**
